/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musteri_takip;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static musteri_takip.musteri_takip_fm1.xx;

/**
 *
 * @author Optical
 */
public class kaydol_giris extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    Statement st;
    
    /**
     * Creates new form musteri_takip
     */
    public kaydol_giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_kaydol_kullanici_adi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField_kaydol_sifre = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_kaydol_sifre_tekrar = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_kaydol_gmail = new javax.swing.JTextField();
        jButton_kaydol_kaydol = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_giris_kullanici_adi = new javax.swing.JTextField();
        jPasswordField_giris_sifre = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_giris_giris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(372, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kaydol");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Kullanıcı Adı");

        jTextField_kaydol_kullanici_adi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_kaydol_kullanici_adi.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_kaydol_kullanici_adi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Şifre");

        jPasswordField_kaydol_sifre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordField_kaydol_sifre.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField_kaydol_sifre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Şifre Tekrarı");

        jPasswordField_kaydol_sifre_tekrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordField_kaydol_sifre_tekrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Gmail");

        jTextField_kaydol_gmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_kaydol_gmail.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_kaydol_gmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));

        jButton_kaydol_kaydol.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton_kaydol_kaydol.setForeground(new java.awt.Color(153, 0, 0));
        jButton_kaydol_kaydol.setText("Kaydol");
        jButton_kaydol_kaydol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_kaydol_kaydol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_kaydol_kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kaydol_kaydolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_kaydol_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_kaydol_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_kaydol_sifre_tekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_kaydol_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButton_kaydol_kaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextField_kaydol_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPasswordField_kaydol_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPasswordField_kaydol_sifre_tekrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextField_kaydol_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton_kaydol_kaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giriş");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 14));

        jTextField_giris_kullanici_adi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_giris_kullanici_adi.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_giris_kullanici_adi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jPasswordField_giris_sifre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jPasswordField_giris_sifre.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField_giris_sifre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Şifre");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kullanıcı Adı");

        jButton_giris_giris.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton_giris_giris.setForeground(new java.awt.Color(153, 0, 0));
        jButton_giris_giris.setText("Giriş");
        jButton_giris_giris.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jButton_giris_giris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_giris_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_giris_girisActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(36, 36));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setPreferredSize(new java.awt.Dimension(36, 36));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_giris_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField_giris_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_giris_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextField_giris_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPasswordField_giris_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_giris_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(815, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton_giris_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_giris_girisActionPerformed
        String kullanici_adi,sifre;
        kullanici_adi = jTextField_giris_kullanici_adi.getText();
        sifre = jPasswordField_giris_sifre.getText();
        
        if(kullanici_adi.equals("")||sifre.equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "Some  Date is Missing","Place Fill All Boxes",1);
            
        }
        else{
            
            try {
                con = Connectionz.getConnection();//Connectionz.java dosyası burası (class)
                pst = con.prepareStatement("SELECT * FROM LOGIN_TABLE WHERE USER_NAME=? AND PASSWORD=?");
                
                pst.setString(1, kullanici_adi);// 1 (?), sorgudaki ilk parametreyi belirtir
                pst.setString(2, sifre);// 2 (?), sorgudaki ilk parametreyi belirtir
                
                rs = pst.executeQuery();
                
                if(rs.next()){
                    
                    String dbkulanici_adi = rs.getString("USER_NAME");
                    
                    musteri_takip_fm1 fm1 = new musteri_takip_fm1(dbkulanici_adi);
                    
                    fm1.setVisible(true);
                    setVisible(false);
                    
                }
            } 
            catch (Exception ex) {
                System.out.println(""+ ex);
            }
            
        }
    }//GEN-LAST:event_jButton_giris_girisActionPerformed
    
    public int sorgu(String kullanicii){
        int sayac = 0;
        con = Connectionz.getConnection();
        
        try {
            
            st = con.createStatement();
            rs=st.executeQuery("SELECT * FROM LOGIN_TABLE WHERE USER_NAME='"+kullanicii+"'");
            while(rs.next()){
                sayac++;
            }
        }
        catch (Exception ex) {
            System.out.println("hata: "+ex);
        }
        
        return sayac;
        
    }
    
    public void ekle(){
        
        if(sorgu(jTextField_kaydol_kullanici_adi.getText())!=0){
            JOptionPane.showMessageDialog(this,"Bu kullanıcı daha önce alınmıştır !!");
        }
        else{
            String username = jTextField_kaydol_kullanici_adi.getText();
            String password = jPasswordField_kaydol_sifre.getText();
            String gmail = jTextField_kaydol_gmail.getText();

            try{
                con = Connectionz.getConnection();
                pst = con.prepareStatement("INSERT INTO LOGIN_TABLE (USER_NAME,PASSWORD,GMAIL) VALUES (?,?,?)");

                pst.setString(1, username);
                pst.setString(2, password);
                pst.setString(3, gmail);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "KAYIT BAŞARIYLA GERÇEKLEŞTİRİLDİ");
            }
            catch(Exception ex){
                System.out.println(""+ ex);
            }
        }
        
    }
    
    public static boolean email_kontrol(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
    
    private void jButton_kaydol_kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kaydol_kaydolActionPerformed
        String kullanici_adi, gmail, sifre, sifre_tekrari;
        int sifre_length = 30;

        kullanici_adi = jTextField_kaydol_kullanici_adi.getText().toUpperCase();// Büyük Harf yapıyor .toUpperCase()
        gmail = jTextField_kaydol_gmail.getText().toUpperCase();

        sifre = jPasswordField_kaydol_sifre.getText();
        sifre_tekrari = jPasswordField_kaydol_sifre_tekrar.getText();

        // şifrenin uzunluğu 8'den küçük ve sifre_length den büyük olursa aşağıdakini
        // uygula
        if (sifre.length() < 8 || sifre.length() > sifre_length) {
            JOptionPane.showMessageDialog(this, "Şifre alanına min. 8 karakter max. 30 karakter giriniz!");
        }

        // şifrenin uzunluğu 8 ile sifre_length arasında olursa devam et
        else if (sifre.length() >= 8 && sifre.length() <= sifre_length) {

            // sifre ve tekrar girilen şifre eşit ise devam et
            if (sifre.equals(sifre_tekrari) == true) {

                String upperCaseChars = "(.*[A-Z].*)";

                // Şifrede büyük harf içeriyorsa devam et
                if (sifre.matches(upperCaseChars)) {

                    String num = "(.*[0-9].*)";

                    // Şifrede en az 1 adet sayı var ise devam et
                    if (sifre.matches(num)) {

                        String specialChar = "(.*[~,!,@,#,$,%,^,&,*,(,),.,-,_,=,+,[,{,],},|,;,:,<,>,/,?].*$)";

                        // Şifre en az bir adet özel karakter içeriyorsa devam et
                        if (sifre.matches(specialChar)) {

                            // Email içinde @ ve .com .org vb var ise devam et
                            String email = jTextField_kaydol_gmail.getText();
                            if (email_kontrol(email)) {
                                
                                
                                
                                
                                
                                ekle();
                                
                                
                                
                                
                                

                            }

                            // Email doğru değil ise aşağıdakini yap
                            else {
                                JOptionPane.showMessageDialog(this, "Yanlış Email");
                            }
                        }

                        // Şifre en az bir adet özel karakter yoksa aşağıdakini yap
                        else {
                            JOptionPane.showMessageDialog(this, "Şifreniz en az 1 adet özel karakter içermeli");
                        }

                    }

                    // Şifrede en az 1 adet sayı yok ise aşağıdakini yap
                    else {
                        JOptionPane.showMessageDialog(this, "Şifreniz en az 1 adet sayı içermeli");
                    }
                }

                // Şifrede 1 tane büyük harf yoksa aşağıdakini yap
                else {
                    JOptionPane.showMessageDialog(this, "Şifreniz en az 1 Büyük karakter içermeli");
                }

            }

            // şifre ile tekrar girilen şifre eşit değil ise
            else {
                JOptionPane.showMessageDialog(this, "Şifreler Eşleşmiyor");
            }
        }

        // Hepsinde hata alırsak
        else {

        }
    }//GEN-LAST:event_jButton_kaydol_kaydolActionPerformed
    static int xx,yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kaydol_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kaydol_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kaydol_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kaydol_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kaydol_giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_giris_giris;
    private javax.swing.JButton jButton_kaydol_kaydol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_giris_sifre;
    private javax.swing.JPasswordField jPasswordField_kaydol_sifre;
    private javax.swing.JPasswordField jPasswordField_kaydol_sifre_tekrar;
    private javax.swing.JTextField jTextField_giris_kullanici_adi;
    private javax.swing.JTextField jTextField_kaydol_gmail;
    private javax.swing.JTextField jTextField_kaydol_kullanici_adi;
    // End of variables declaration//GEN-END:variables
}
